---
- name: Copy Theme
  copy: src=~/.dotfiles/zsh/veggiemonk.zsh-theme dest=~/.oh-my-zsh/themes/
  when: cloned|success
  sudo: no

- name: Install base16-shell theme
  git:
    repo=https://github.com/chriskempson/base16-shell
    dest=~/.config/base16-shell
    accept_hostkey=yes
  sudo: no
